import React from "react";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ background: '#222', color: '#fff', overflow: 'hidden' }}>
        {children}
      </body>
    </html>
  )
}